url: https://nullpointerexception1.wordpress.com/
database:
  # the name of the JDBC driver, mysql in our case
  driverClass: com.mysql.jdbc.Driver
  # the username
  user: root
  #user: root
  # the password
  password: rishabh69
  #password:
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:mysql://localhost:3306/myDatabase
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect